# Generated by Django 5.0.3 on 2024-03-20 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokomizsuariapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='CustomerID',
            field=models.IntegerField(),
        ),
    ]
