# Generated by Django 5.0.3 on 2024-03-20 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokomizsuariapp', '0002_alter_customer_customerid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryID', models.IntegerField()),
                ('CategoryName', models.CharField(max_length=25)),
                ('Description', models.TextField(blank=True)),
            ],
        ),
    ]
