# Generated by Django 5.0.3 on 2024-03-20 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokomizsuariapp', '0006_employee_remove_customer_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderDetailID', models.IntegerField()),
                ('OrderID', models.IntegerField()),
                ('ProductID', models.IntegerField()),
                ('Quantity', models.IntegerField()),
            ],
        ),
    ]
