# Generated by Django 5.0.3 on 2024-03-20 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokomizsuariapp', '0007_orderdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderID', models.IntegerField()),
                ('CustomerID', models.IntegerField()),
                ('EmployeeID', models.IntegerField()),
                ('OrderDate', models.DateField()),
                ('ShipperID', models.IntegerField()),
            ],
        ),
    ]
