# Generated by Django 5.0.3 on 2024-03-20 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokomizsuariapp', '0009_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShipperID', models.IntegerField()),
                ('ShipperName', models.CharField(max_length=25)),
                ('Phone', models.CharField(max_length=25)),
            ],
        ),
    ]
