# Generated by Django 5.0.3 on 2024-03-21 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokomizsuariapp', '0013_customer_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='image',
            new_name='image_display',
        ),
    ]
