# Generated by Django 5.0.3 on 2024-03-21 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokomizsuariapp', '0015_remove_customer_image_display_customer_image_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='image_tag',
        ),
        migrations.AddField(
            model_name='customer',
            name='image_display',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
