# Generated by Django 5.0.3 on 2024-03-21 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokomizsuariapp', '0018_rename_image_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
