# Generated by Django 5.0.3 on 2024-03-21 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokomizsuariapp', '0020_product_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
