# Generated by Django 5.0.3 on 2024-03-21 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokomizsuariapp', '0021_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductID', models.AutoField(primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=25)),
                ('SupplierID', models.IntegerField()),
                ('CategoryID', models.IntegerField()),
                ('Unit', models.CharField(max_length=25)),
                ('Price', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('description', models.TextField()),
            ],
        ),
    ]
