# Generated by Django 5.0.3 on 2024-03-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokomizsuariapp', '0024_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('ProductID', models.AutoField(primary_key=True, serialize=False)),
                ('Nama', models.CharField(max_length=25)),
                ('Email', models.EmailField(max_length=254)),
                ('Message', models.TextField()),
            ],
        ),
    ]
